_target_: src.models.OperatorFormerModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 8.0e-4
  weight_decay: 1.0e-4

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# scheduler:
#   _target_: torch.optim.lr_scheduler.OneCycleLR
#   _partial_: true
#   max_lr: ${model.optimizer.lr}
#   total_steps: ${trainer.max_epochs}
#   div_factor: 1.0e-8
#   pct_start: 0.2
#   final_div_factor: 1.0e-8

net:
  _target_: src.models.components.OperatorFormer
  input_encoder_config:
    _target_: src.models.components.dataclass_config.InputEncoderConfig
    attn_type: "fourier"
    in_features: 1
    out_features: 96
    d_model: 96
    nhead: 8
    dim_feedforward: 96
    num_layers: 8
    scale: [8, 4, 4, 2, 1, 1, 1, 1]
    dropout: 0.05
    activation: "geglu"
    norm_first: true
    bias: false
    norm_config:
      _target_: src.models.components.dataclass_config.NormlizationConfig
      method: "InstanceNorm"
      eps: 1.0e-5
      elementwise_affine: true
      affine: false
    init_config:
      _target_: src.models.components.dataclass_config.ParamInitConfig
      method: "xavier"
      gain: 1.0e-6
      diagonal_weight: 1.0e-9
    pos_config:
      _target_: src.models.components.dataclass_config.PosEncodingConfig
      method: "RoPE"
      dim: 1
      min_freq: 0.015625
      scale: 1
  query_encoder_config:
    _target_: src.models.components.dataclass_config.QueryEncoderConfig
    in_features: 1
    d_model: 96
    bias: false
    scale: 2
  crossattention_encoder_config:
    _target_: src.models.components.dataclass_config.CrossAttentionEncoderConfig
    attn_type: "fourier"
    d_model: 96
    nhead: 8
    dim_feedforward: 96
    num_layers: 1
    scale: 1
    dropout: 0.05
    activation: "geglu"
    norm_first: true
    bias: false
    residual: true
    norm_config:
      _target_: src.models.components.dataclass_config.NormlizationConfig
      method: "InstanceNorm"
      eps: 1.0e-5
      elementwise_affine: true
      affine: false
    init_config:
      _target_: src.models.components.dataclass_config.ParamInitConfig
      method: "xavier"
      gain: 1.0e-6
      diagonal_weight: 1.0e-9
    pos_config:
      _target_: src.models.components.dataclass_config.PosEncodingConfig
      method: "RoPE"
      dim: 1
      min_freq: 0.015625
      scale: 1
  propagator_decoder_config:
    _target_: src.models.components.dataclass_config.PropagatorDecoderConfig
    d_model: 96
    out_features: 1
    num_layers: 8
    bias: True

# compile model for faster training with pytorch 2.0
compile: false
