# @package _global_

defaults:
  - override /hydra/launcher@_here_: submitit_slurm

hydra:
  launcher:
    gpus_per_task: 1
    partition: LocalQ
    array_parallelism: 256
    nodes: 1
    tasks_per_node: 2
