defaults:
  - model_checkpoint
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  every_n_epochs: 10
  save_last: True
  save_on_train_epoch_end: True
  auto_insert_metric_name: False

model_summary:
  max_depth: -1
